version: '3'
services:
  faucet:
    build: ./faucet
    ports:
      - 8080:8080
    environment:
      - API_PORT=8080
      - WEB3_PROVIDER=http://127.0.0.1:8545
      - FAUCET_STORAGE_CONTRACT_ADDRESS=0xC34B99cBbBb2ac098F87c811f7A3b51cc65b186f
      - UNLOCKED_ACCOUNT=0x917441412223Ac1104617Ca07ca9853504BEA5d0
