
= `ConfigStorage.sol`
The `ConfigStorage.sol` smart contract is the central component of the Knowledge Base. It stores all the configuration data of the Knowledge Base. The configuration data is stored in various mappings and parameters. The conract also contains functions to set and get the configuration data. The `ConfigStorage.sol` smart contract inherits the `BaseConfigAdmin.sol` smart contract. The `BaseConfigAdmin.sol` smart contract contains functions to add and remove admins and contract admins.

The system differentiated between two types of admins:

* *User Admin* - The user admin can be a professor, teaching assistant or system admin. User admins can change the configuration of the system and add and remove admins.
* *Contract Admin* - The contract admin are contracts that need special permissions to interact with the Knowledge Base. Usually all contracts that are part of the Knowledge Base are contract admins.

This role management system is used to ensure that only trusted users or contracts can access or change the configuration data of the Knowledge Base. This is especially important for the `SBCoin.sol` and validator smart contract. Because only admins should be allowed to transfer _Knowledge Coins_.

== Parameters
The `ConfigStorage.sol` smart contract stores the configuration data in various parameters. The parameters are used to store the configuration data in a more efficient way. The parameters are:

* `uint128 faucetGas;` - The amount of gas the faucet can send to a user.
* `uint128 faucetBlockNoDifference;` - The amount of blocks need to be passed before the faucet can be used again.

=== Inherited parameters from `BaseConfigAdmin.sol`
The `ConfigStorage.sol` smart contract inherits the following parameters from the `BaseConfigAdmin.sol` smart contract:

* `address[] private admins;` - Stores the addresses of the admins.
* `ContractAdmin[] private contractAdmins;` - Stores the contract admins.

== Mappings
The `ConfigStorage.sol` smart contract stores the configuration data in various mappings. The mappings are used to store the configuration data in a more efficient way. The mappings are:

* `mapping(uint256 => NOWSemester) semesters;` - Stores the semesters of the Knowledge Base. The key of the mapping is the semester ID. The value of the mapping is a `NOWSemester` struct.

== Structs
The `ConfigStorage.sol` smart contract stores the configuration data in various structs. The structs are used to store the configuration data in a more efficient way. The structs are:


* `struct NOWSemester {...}` - Stores the data of a semester. The struct contains the following parameters: 
[source,solidity]
----
struct NOWSemester {
    string name; // Name of the semester (e.g. SS22)
    uint256 startBlock; // First block which counts towards this semester
    uint256 endBlock; // Last block which counts towards this semester
    uint256 minKnowledgeCoinAmount; // Amount of knowledge Coins needed to take exam
    uint256 assignmentCounter; // Assignment counter
    uint256[] assignmentIds; // Assignment Ids
    mapping(uint256 => NOWAssignments) assignments; // Assigned assignments
    // TEMP VARIABLES
    uint256 assignmentStartBlock; // Temp var to keep track of lowest start block of all assignments
    uint256 assignmentEndBlock; // Temp var to keep track of highest end block of all assignments
}
----

* `struct NOWAssignment {...}` - Stores the data of an assignment. The struct contains the following parameters:
[source,solidity]
----
struct NOWAssignments {
    string name; // Name of the assignment
    string link; // Link to the assignment
    address validationContractAddress; // Address to the validation contract
    uint256 startBlock; // First block which counts towards this assignment
    uint256 endBlock; // Last block which counts towards this assignment
}
----

=== Inhertited structs from `BaseConfigAdmin.sol`
The `ConfigStorage.sol` smart contract inherits the following structs from the `BaseConfigAdmin.sol` smart contract:

* `struct ContractAdmin {...}` - Stores the data of an admin. The struct contains the following parameters:
[source,solidity]
----
struct ContractAdmin {
    string contractName; // Name of contract
    address contractAddress; // Address of contract
    bool isContractAdmin; // Is contract admin
}
----

== Functions
The `ConfigStorage.sol` smart contract contains various functions. The paramaters, mappings and structs are used in the functions and can be setted or getted. For detailed descriptions of the functions, please see the comments in the `ConfigStorage.sol` smart contract.