
= `SBCoin.sol`
The `SBCoin.sol` smart contract is the contract which stores the _Knowledge Coin_ in short _NOW_. This coin is the main currency of the Knolwedge Base system and the payment students receive for successfully passing tests on their submitted assignments.

All the functions of the contract are described in the comments to the code. The contract is written in Solidity language and compiled with the help of the `solc` compiler.

== Security

All minting, transfer or burning functions are restricted to user or contract admins. This ensures that only the contract owner can mint new coins and that only the contract owner or the contract admin can transfer coins to other users. So students cannot send coins to each other to cheat the system.

To ensure that students cannot reuse the Knowledge Coins from a previous semester, the Knowledge Coins are bounded to a block range. So students can only use the Knowledge Coins they received in the current semester for qualifying themselves for the current semester exam. This is done by the `mint` function. The `mint` function can only be called by user or contract admins and sends the amount of Knowledge Coins to the student's address and logs the amount with the current block number.

The `burn` function can burn Knowledge Coins from the student's address. This function is also restricted to user or contract admins. Coins are burned by transfering them to a 0x0 address using the `_transfer` function.

The basic `_transfer` and `_approve` functions can only be called by user or contract admins. The `_transfer` function is used to transfer Knowledge Coins from one address to another. The `_approve` function is used to approve another address to spend a certain amount of Knowledge Coins from the sender's address.

The `_transfer` function also keeps track of the change of coins for the block number restriction.