= How to install a new Raspberry Pi node

To provide a decentralized network there need to be different nodes rather than one central server.
If one node is missing, the system won´t work, so the setup has to be restarted. The number of nodes is set to 6.
The following steps will guide you through the installation process.

== Tools needed

* Raspberry Pi
* SD card
* SD card reader
* Ethernet cable or WiFi
* USB keyboard
* USB mouse
* Micro HDMI to HDMI/Display port cable or adapter
* Power supply
* Own PC
* USB stick with needed files for creating the etherum node

== Possible Pi purposes and combinations
Pi´s can be used for the following purposes:

* Miner
* RPC node
* Frontend
* Faucet

A Pi can either be a miner or an RPC node, but not both at the same time. This is because of security issues.
The frontend can run on every node, but it makes sense to run it on an RPC node, because it is the only node that grants access to the network.
The faucet should not be on the same Pi as the RPC node, because it needs an unlocked account to send ether to the users. This is a security issue.
