name: Node.js CI

on:
  push:
    branches: ["feature/smart-contracts"]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: web3

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./web3/package-lock.json"
      - run: cd web3 && npm ci
      - run: cd web3 && npm run build --if-present
      - run: cd web3 && npm test
