name: Run web3 tests
on: push

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      ganache:
        # Docker Hub image
        image: trufflesuite/ganache:latest
        # Port
        ports:
          - 8545:8545
        env:
          miner.coinbase: "0xF5F07Df523774d6d4a7dBBb3C41e35de93d3B0C0"
          account: "0x4e1904f05788517969a3c4c9a9ceee40722c0640878dd70dc315b43381c118c2,1000000000000000000000"
          unlock: "0x4e1904f05788517969a3c4c9a9ceee40722c0640878dd70dc315b43381c118c2"
          chain.chainId: "1998"

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    env:
      ENV: test

    steps:
      - name: Upgrade NPM
        run: npm install -g npm
      - uses: actions/checkout@v3
      - name: Run ganache-cli - using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./web3/package-lock.json"
      - run: npm ci
        working-directory: web3
      - run: npm run build --if-present
        working-directory: web3
      - run: npm test
        working-directory: web3
