name: Run web3 tests
on: push

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      ganache:
        # Docker Hub image
        image: trufflesuite/ganache:latest
        # Port
        ports:
          - 8545:8545
        env:
          miner.coinbase: "0xF5F07Df523774d6d4a7dBBb3C41e35de93d3B0C0"
          account: "0x4e1904f05788517969a3c4c9a9ceee40722c0640878dd70dc315b43381c118c2,1000000000000000000000"
          unlock: "0x4e1904f05788517969a3c4c9a9ceee40722c0640878dd70dc315b43381c118c2"

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3

      # Performs a clean installation of all dependencies in the `package.json` file
      # For more information, see https://docs.npmjs.com/cli/ci.html
      - name: Install dependencies
        run: npm ci

      - name: Run tests
        # Runs a script that creates a PostgreSQL table, populates
        # the table with data, and then retrieves the data.
        run: npm test
