name: Run web3 tests
on: push

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    #services:
    # Label used to access the service container
    #  ganache:
    # Docker Hub image
    #    image: elianderlohr/ganache-docker:ganache-docker
    # Port
    #    ports:
    #      - 8545:8545

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    env:
      ENV: test

    steps:
      - name: Upgrade NPM
        run: npm install -g npm
      - uses: actions/checkout@v3
      - name: Run ganache-cli - using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./web3/package-lock.json"
      - uses: addnab/docker-run-action@v3
        with:
          registry: docker.io
          image: trufflesuite/ganache:latest
          options: -v ${{ github.workspace }}:/work -e chain.chainId=1998
      - run: npm ci
        working-directory: web3
      - run: npm run build --if-present
        working-directory: web3
      - run: npm test
        working-directory: web3
