name: Run web3 tests
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    paths:
      - frontend/web3/**

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      ganache:
        # Docker Hub image
        image: trufflesuite/ganache:latest # elianderlohr/ganache-docker:ganache-docker
        # Port
        ports:
          - 8545:8545

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    env:
      ENV: test
      CI: true

    steps:
      - name: Upgrade NPM
        run: npm install -g npm
      - uses: actions/checkout@v3
      - name: Deploy contracts - using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./frontend/package-lock.json"
      - run: cd smart-contracts && npm i
      - run: npm --prefix ./smart-contracts run github
      - name: Install dependencies - using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./frontend/package-lock.json"
      - run: cd frontend && npm i
      - run: cd frontend && npm run test_web3
